### ISSUE TITLE
Issues Encountered

### ISSUE THREAD

**Issue by GuilleChacon** [renero/dataset#6]
I've been using the dataset package with the Github provided and some functions are giving outputs different and the ones shown:

1)  data.num_features  and  data.num_samples not recognized and deliver error

2)  data.plot_histogram('Total') doesn't work, I had yo use the regular panda plot

3) correlations functions has several issues:

a) data.correlated(threshold = X) doesn't show the same output as mentioned (see attached photo)

b) data.numerical_correlated  and data.categorical_correlated shows a different output and threshold doesn't affect it  (see attached photo)

4)  data.skewed_features() doesn't give output

5) data.add_columns doesn't work with one variable adds (see example attached), it still works if you extract all the categoricals (it says there is a mismatch with the Panda Frame)

6) discretize doesn't turn into categorical value (see Example), this has several problems with other functions (like fix_skewness or scale sends an error), this issue isn't solved with "to_categorical" either. My only solution was to turn it into categorical before and then using "merge" instead of "discretize"

also, be careful with

Fix_skewness works over onehot_encode variables

**Comment by renero** [comment]
Thanks for the feedback! I'll re-check all of them and add more tests to the package.
For some reason I've problems with the photos you mention... I cannot see anything.
Could you please add some reproducible background? What dataset areyou using, and the sequence of operations that lead to the disaster? :-)

Thanks!!

**Comment by GuilleChacon** [comment]
This are the photos of the problems i've encountered

the database in use is the follorwing [https://raw.githubusercontent.com/GuilleChacon/Machine-Learning-II/master/turnover.csv](url)

and the code that was testing them is the following:
[https://github.com/GuilleChacon/Machine-Learning-II/blob/master/AssignmentIML.ipynb](url)

Most of the errors i've removed them, if you need to i can add them (let me know if the photos now are clear)

Best Regards

![Add columns](https://user-images.githubusercontent.com/60391342/74518559-5e677480-4f14-11ea-97e5-bac43275152d.png)
![Categorical Correlated](https://user-images.githubusercontent.com/60391342/74518563-5f000b00-4f14-11ea-953b-795b57c54334.png)
![correlated](https://user-images.githubusercontent.com/60391342/74518564-5f98a180-4f14-11ea-99bc-196b0fb876f1.png)
![Discretize](https://user-images.githubusercontent.com/60391342/74518566-5f98a180-4f14-11ea-8304-ba3720d0cf08.png)

**Comment by renero** [comment]
Thanks!!
I'll work on it asap!

**Comment by renero** [comment]
After trying to reproduce all of them with the latest version, I added more controls on 0.16.4, but couldn't find any of the issues submitted. So I'm closing this issue.
